---
- name: Get Ethereum Block Number
  hosts: web_servers
  become: false
  gather_facts: false

  tasks:
    - name: Send HTTP request to get Ethereum block number on port 8575
      raw: "curl -X POST -H 'Content-Type: application/json' --data '{\"method\": \"eth_blockNumber\", \"params\": [], \"id\": 1, \"jsonrpc\": \"2.0\" }' http://127.0.0.1:8575"
      register: response_8575

    - name: Display Ethereum block number on port 8575
      debug:
        var: response_8575.stdout

    - name: Send HTTP request to get Ethereum block number on port 8580
      raw: "curl -X POST -H 'Content-Type: application/json' --data '{\"method\": \"eth_blockNumber\", \"params\": [], \"id\": 1, \"jsonrpc\": \"2.0\" }' http://127.0.0.1:8580"
      register: response_8580

    - name: Display Ethereum block number on port 8580
      debug:
        var: response_8580.stdout

    - name: Send HTTP request to get Ethereum block number on port 8585
      raw: "curl -X POST -H 'Content-Type: application/json' --data '{\"method\": \"eth_blockNumber\", \"params\": [], \"id\": 1, \"jsonrpc\": \"2.0\" }' http://127.0.0.1:8585"
      register: response_8585

    - name: Display Ethereum block number on port 8585
      debug:
        var: response_8585.stdout

