---
- name: Clone Qitmeer/qng repository and Run Commands on Web Servers
  hosts: web_servers
  become: true
  remote_user: ubuntu

  tasks:
    - name: Clone the Qitmeer/qng repository
      git:
        repo: https://github.com/Qitmeer/qng.git
        dest: /home/ubuntu/qng
        update: yes
        force: yes

    - name: Run make command with updated PATH
      ansible.builtin.shell:
        cmd: "PATH=$PATH:/usr/local/go/bin make"
        chdir: /home/ubuntu/qng

    - name: Create directories node1, node2, and node3
      ansible.builtin.file:
        path: "/home/ubuntu/node{{ item }}"
        state: directory
      loop: [1, 2, 3]

    - name: Copy qng to nodes
      ansible.builtin.shell:
        cmd: "sudo cp /home/ubuntu/qng/build/bin/qng /home/ubuntu/node{{ item }}"
      loop: [1, 2, 3]

    - name: Copy mgh21.py to the remote server
      copy:
        src: "{{ inventory_dir }}/mgh21.py"
        dest: /home/ubuntu/mgh21.py
        mode: 0755

    - name: Run mgh21.py script on the remote server
      ansible.builtin.command: python3 mgh21.py
      args:
        chdir: /home/ubuntu/
    - name: Set ownership for node1 directory
      ansible.builtin.command:
        cmd: "sudo chown -R ubuntu:ubuntu /home/ubuntu/node1"
      args:
        chdir: "~/"

    - name: Set ownership for node2 directory
      ansible.builtin.command:
        cmd: "sudo chown -R ubuntu:ubuntu /home/ubuntu/node2"
      args:
        chdir: "~/"

    - name: Set ownership for node3 directory
      ansible.builtin.command:
        cmd: "sudo chown -R ubuntu:ubuntu /home/ubuntu/node3"
      args:
        chdir: "~/"
    - name: Create password.txt in /home/ubuntu
      ansible.builtin.copy:
        content: "amana1"
        dest: "/home/ubuntu/password.txt"

    - name: Copy password.txt to node directories
      ansible.builtin.copy:
        src: "/home/ubuntu/password.txt"
        dest: "{{ item }}/password.txt"
        remote_src: yes
      loop:
        - "/home/ubuntu/node1"
        - "/home/ubuntu/node2"
        - "/home/ubuntu/node3"
      become: true
